In [ ]:
## Este código implementa o algoritmo A-Estrela para resolver o problema do Quebra-Cabeça de Oito Peças

## Definição do funcionamento do jogo

In [1]:
import numpy as np

In [2]:
## Definição do tabuleiro
# initial_puzzle = np.asarray([[1,2,3],
#                              [4,None, 5],
#                              [6,7,8 ]])

initial_puzzle = np.asarray([[1,2,3,4],
                             [5,6,7,8],
                             [9,10,None,12],
                             [13,14,15,16]])

objective_puzzle = np.asarray([[1,2,3,4],
                               [5,6,7,8],
                               [9,10,12,13],
                               [14,15,16, None]])


## Define as regras de movimentações:
rule_action = {
    'top': (-1, 0),
    'bottom': (1, 0),
    'left': (0, -1),
    'right': (0, 1)
}


puzzle_shape = (4, 4)

if not puzzle_shape == initial_puzzle.shape:
    raise 'O tabuleiro inicial é obrigado a obedecer o puzzle_shape'

In [3]:
def h1(puzzle):
    global objective_puzzle
    
    '''
        Esta heurística consiste em contabilizar quantas peças estão em locais errados.
        Esta é uma heurística simples.
    '''
    
    return (puzzle != objective_puzzle).sum()

In [4]:
def h2(puzzle):
    global objective_puzzle
    
    '''
        Esta heurística consiste em calcular a distância de manhattan de cada peça até sua posição objetivo.
    '''
    distancias_manhattan = []
    
    for i in range(puzzle.shape[0]):
        for j in range(puzzle.shape[1]):
            position = np.where(objective_puzzle == puzzle[i][j])
            
            distancias_manhattan.append( int(abs(i - position[0]) + abs(j - position[1])) )
    
    return np.asarray(distancias_manhattan).sum()

In [5]:
## Função de ação no tabuleiro
def expands_new_states(father_puzzle):
    global rule_action
    
    
    actions = []
    children_puzzles = []
    
    ## Itera todas as possíveis ações para expandir os novos estados.
    for act in rule_action.keys():
        ## Pega a posição do espaço vazio do tabuleiro
        position = np.where(father_puzzle == None)

        ## Realiza a ação de movimentar a peça vazia.
        new_position = (position[0] + rule_action[act][0], position[1] + rule_action[act][1])
        
        if action_is_valid(new_position):
            actions.append(act)
            child_puzzle = father_puzzle.copy()
            print('Ação: {}'.format(act))
            ## Atualiza o tabuleiro com o novo estado, após o movimento da posição vazia do tabuleiro.
            child_puzzle[position] = child_puzzle[new_position]
            child_puzzle[new_position] = None
            
            children_puzzles.append(child_puzzle)
    
    return (actions, children_puzzles)


## Função para avaliar quais são os possíveis movimentos.
def action_is_valid(new_position):
    global puzzle_shape
    max_height = puzzle_shape[0]
    max_width = puzzle_shape[1]
    
    if new_position[0] >= 0 and new_position[0] < max_height and new_position[1] >= 0 and new_position[1] < max_width:
        return True

In [6]:
expands_new_states(initial_puzzle)

Ação: top
Ação: bottom
Ação: left
Ação: right


(['top', 'bottom', 'left', 'right'],
 [array([[1, 2, 3, 4],
         [5, 6, None, 8],
         [9, 10, 7, 12],
         [13, 14, 15, 16]], dtype=object),
  array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 15, 12],
         [13, 14, None, 16]], dtype=object),
  array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, None, 10, 12],
         [13, 14, 15, 16]], dtype=object),
  array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 12, None],
         [13, 14, 15, 16]], dtype=object)])

## Algoritmo A*